"""Initial database schema

Revision ID: 57c80c08bbd3
Revises: 
Create Date: 2021-06-12 10:48:23.518811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c80c08bbd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stackoverflow_schema',
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False, comment='The year of the row the data represented'),
    sa.Column('columns', sa.JSON(), nullable=False, comment='The columns represented by the year'),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('stackoverflow_response',
    sa.Column('row_id', sa.Text(), nullable=False, comment='Common ID of the response'),
    sa.Column('response_id', sa.Integer(), nullable=True, comment='The anonymized ID of the response'),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False, comment='The responses in JSON corresponding to the year of the data'),
    sa.ForeignKeyConstraint(['year'], ['stackoverflow_schema.year'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stackoverflow_response')
    op.drop_table('stackoverflow_schema')
    # ### end Alembic commands ###
