"""Initial database schema

Revision ID: fb55034feb6a
Revises: 
Create Date: 2021-06-12 22:01:15.365405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb55034feb6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stackoverflow_schema',
    sa.Column('insight_year', sa.Integer(), autoincrement=False, nullable=False, comment='The year of the row the data represented'),
    sa.Column('response_columns', sa.JSON(), nullable=False, comment='The columns represented by the year'),
    sa.PrimaryKeyConstraint('insight_year')
    )
    op.create_table('stackoverflow_response',
    sa.Column('id', sa.Text(), nullable=False, comment='Common ID of the response'),
    sa.Column('response_id', sa.Integer(), nullable=True, comment='The anonymized ID of the response'),
    sa.Column('response_year', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False, comment='The responses in JSON corresponding to the year of the data'),
    sa.ForeignKeyConstraint(['response_year'], ['stackoverflow_schema.insight_year'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stackoverflow_response')
    op.drop_table('stackoverflow_schema')
    # ### end Alembic commands ###
